version: '3.9'  # Usar 3.9 para mayor compatibilidad

services:
  cac_postgres:
    image: postgres:16-alpine
    container_name: cac_postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - cac_postgres:/var/lib/postgresql/data

  cac_pgadmin:
    image: dpage/pgadmin4
    container_name: cac_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - cac_pgadmin:/var/lib/pgadmin
    depends_on:
      - cac_postgres
    networks:
      - default

volumes:
  cac_postgres:
  cac_pgadmin:

networks:
  default:
    name: cac_sql